### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by wallanbrewer**

### CODE REVIEW

**Comment by wallanbrewer** [comment]
Initial WebSite

**Comment by chasebrewsky** [comment]
Sorry I just got around to this. Yeah this looks good! You got the gist of it.

**Comment by wallanbrewer** [comment]
Slowly but surely.  Now it's learning code.  Is there easier way to view page as I change line of code within visual studio than going out and opening index.html to see result?


Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by chasebrewsky** [comment]
Yeah you can use the LiveServer plugin: https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer

**Comment by wallanbrewer** [comment]
Saw youtube vid than mentioned that one.  Also another called prettier.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wallanbrewer** [comment]
All installed via visual studio extensions.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
